[build]
    command = "npm run build"
    publish = "dist"

[context.production.environment]
    ELEVENTY_ENV = "production"

[context.staging.environment]
    ELEVENTY_ENV = "staging"

# For header information see https://www.netlify.com/docs/netlify-toml-reference/

[[headers]]
    for = "/*"
    [headers.values]
        X-Frame-Options = "DENY"
        X-XSS-Protection = "1; mode=block"
        X-Content-Type-Options = "nosniff"
        Referrer-Policy= "no-referrer-when-downgrade"
    for = "/embed/*"
    [headers.values]
        X-XSS-Protection = "1; mode=block"
        X-Content-Type-Options = "nosniff"
        Referrer-Policy= "no-referrer-when-downgrade"

[[redirects]]
    from = "*"
    to = "/404"
    status = 404
